# Generated by Django 4.2.1 on 2023-05-28 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savvinova_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormData',
            new_name='Users',
        ),
    ]
